// ~/constants/Key.ts
// Generated from laravel/app/Enums/Key.php (App\Enums\Key)
// Keep this list in sync with backend to avoid key mismatches.

export const Key = {
    ADD_BLOCK: 'addBlock',
    ADD_NODE: 'addNode',
    ANCHOR: 'anchor',
    AUTO: 'auto',
    CHECKBOX: 'checkbox',
    CPY_BLOCK: 'cpyBlock',
    CPY_NODE: 'cpyNode',
    DATA_MAP: 'dataMap',
    DATA_MAP_JOINT_ID: 'dataMapJointId',
    DEL_BLOCK: 'delBlock',
    DEPTH: 'depth',
    DEP_ID: 'dep_id',
    DIGEST: 'digest',
    DISPLAY: 'display',
    EDGE_TYPE: 'edgeType',
    FIRST_BLOCK_ID: 'firstBlockId',
    FOLD: 'fold',
    HINT: 'hint',
    ICON: 'icon',
    INSTANCE_DETAIL_EDIT: 'instanceDetailEdit',
    INSTANCE_DETAIL_VIEW: 'instanceDetailView',
    INSTANCE_LIST: 'instanceList',
    JOINT: 'joint',
    JOINT_ID: 'jointId',
    LABEL: 'label',
    LAYOUT: 'layout',
    LAYOUT_MAP: 'layoutMap',
    LINE_ID: 'lineId',
    MAX: 'max',
    NODE: 'node',
    NODE_ID: 'nodeId',
    ORDER: 'order',
    PLACEHOLDER: 'placeholder',
    REQUIRED: 'required',
    SRC_KIND: 'srcKind',
    SRC_NODE_LABEL: 'srcNodeLabel',
    S_OPTION: 'sOption',
    TABLE_ID: 'tableId',
    TEMPLATE_DETAIL_EDIT: 'templateDetailEdit',
    TEMPLATE_DETAIL_VIEW: 'templateDetailView',
    TGT_NODE_LABEL: 'tgtNodeLabel',
    TRANSITION: 'transition',
    TYPE: 'type',
    UNIQUE: 'unique',
    VALUE: 'value',
    VAR_NAME: 'varName',
    WORKFLOW: 'workflow',

    SNACKING_CONFIG_ID: 'snackingConfigId',
    LAYOUT_MAP_CONFIG_ID: 'layoutMapConfigId',
    BUTTON_CONFIG_ID: 'buttonConfigId',

    // ボタン系
    ROOT_BULK_CANDIDATE_BTN: 'rootBulkCandidateBtn',
    ROOT_BULK_UPDATE_BTN: 'rootBulkUpdateBtn',
    ROOT_CHECKBOX: 'rootCheckbox',
    ROOT_DELETE_BTN: 'rootDeleteBtn',
    ROOT_EDIT_BTN: 'rootEditBtn',
    ROOT_EDIT_MODE_BTN: 'rootEditModeBtn',
    ROOT_REPOST_BTN: 'rootRepostBtn',
    ROOT_UPDATE_BTN: 'rootUpdateBtn',
    ROOT_VIEW_MODE_BTN: 'rootViewModeBtn',

    ROOT_BASEINFO_BTN: 'rootBaseinfoBtn',
    ROOT_SEND_BTN: 'rootSendBtn',
    ROOT_REPLY_BTN: 'rootReplyBtn',
    ROOT_FORWARD_BTN: 'rootForwardBtn',
    ROOT_OPEN_BTN: 'rootOpenBtn',
    ROOT_CREATE_CANDIDATE_SCHEDULE_BTN: 'rootCreateCandidateScheduleBtn',
    ROOT_CREATE_MESSAGE_BTN: 'rootCreateMessageBtn',

    BUTTON_BULK_CANDIDATE_BTN: 'buttonBulkCandidateBtn',
    BUTTON_BULK_UPDATE_BTN: 'buttonBulkUpdateBtn',
    BUTTON_CHECKBOX: 'buttonCheckbox',
    BUTTON_DELETE_BTN: 'buttonDeleteBtn',
    BUTTON_EDIT_BTN: 'buttonEditBtn',
    BUTTON_EDIT_MODE_BTN: 'buttonEditModeBtn',
    BUTTON_REPOST_BTN: 'buttonRepostBtn',
    BUTTON_UPDATE_BTN: 'buttonUpdateBtn',
    BUTTON_VIEW_MODE_BTN: 'buttonViewModeBtn',

    BUTTON_BASEINFO_BTN: 'buttonBaseinfoBtn',
    BUTTON_SEND_BTN: 'buttonSendBtn',
    BUTTON_REPLY_BTN: 'buttonReplyBtn',
    BUTTON_FORWARD_BTN: 'buttonForwardBtn',
    BUTTON_OPEN_BTN: 'buttonOpenBtn',
    BUTTON_CREATE_CANDIDATE_SCHEDULE_BTN: 'buttonCreateCandidateScheduleBtn',
    BUTTON_CREATE_MESSAGE_BTN: 'buttonCreateMessageBtn',

} as const

export type KeyName = keyof typeof Key
export type KeyValue = typeof Key[KeyName]
